# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Jamie F Olson: Problem Solver"
email: self@jfolson.com
description: > 
  Jamie F Olson is a Data Scientist and Big Data engineer with experience
  across a broad range of industries and technology environments.  He has worked
  with clients in a wide variety of roles including instructor, consultant,
   statistician and software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamiefolson.github.io" # the base hostname & protocol for your site
twitter_username: jamie_f_olson
github_username:  jamiefolson

# Build settings
markdown: kramdown

projects: '/projects/'
research: '/research/'
about: '/about/'
home: '/'
blog: '/blog/'

gems: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-less